#include <SOFAVTK/CellTypeName.h>

#include <unordered_map>

namespace sofavtk
{

std::string getCellTypeName(VTKCellType cellType)
{
#define CELL_TYPE(type) std::make_pair(type, std::string(#type))

    static std::unordered_map<VTKCellType, std::string> cellTypeNames{
        CELL_TYPE(VTK_EMPTY_CELL),
        CELL_TYPE(VTK_VERTEX),
        CELL_TYPE(VTK_POLY_VERTEX),
        CELL_TYPE(VTK_LINE),
        CELL_TYPE(VTK_POLY_LINE),
        CELL_TYPE(VTK_TRIANGLE),
        CELL_TYPE(VTK_TRIANGLE_STRIP),
        CELL_TYPE(VTK_POLYGON),
        CELL_TYPE(VTK_PIXEL),
        CELL_TYPE(VTK_QUAD),
        CELL_TYPE(VTK_TETRA),
        CELL_TYPE(VTK_VOXEL),
        CELL_TYPE(VTK_HEXAHEDRON),
        CELL_TYPE(VTK_WEDGE),
        CELL_TYPE(VTK_PYRAMID),
        CELL_TYPE(VTK_PENTAGONAL_PRISM),
        CELL_TYPE(VTK_HEXAGONAL_PRISM),
        CELL_TYPE(VTK_QUADRATIC_EDGE),
        CELL_TYPE(VTK_QUADRATIC_TRIANGLE),
        CELL_TYPE(VTK_QUADRATIC_QUAD),
        CELL_TYPE(VTK_QUADRATIC_POLYGON),
        CELL_TYPE(VTK_QUADRATIC_TETRA),
        CELL_TYPE(VTK_QUADRATIC_HEXAHEDRON),
        CELL_TYPE(VTK_QUADRATIC_WEDGE),
        CELL_TYPE(VTK_QUADRATIC_PYRAMID),
        CELL_TYPE(VTK_BIQUADRATIC_QUAD),
        CELL_TYPE(VTK_TRIQUADRATIC_HEXAHEDRON),
        CELL_TYPE(VTK_TRIQUADRATIC_PYRAMID),
        CELL_TYPE(VTK_QUADRATIC_LINEAR_QUAD),
        CELL_TYPE(VTK_QUADRATIC_LINEAR_WEDGE),
        CELL_TYPE(VTK_BIQUADRATIC_QUADRATIC_WEDGE),
        CELL_TYPE(VTK_BIQUADRATIC_QUADRATIC_HEXAHEDRON),
        CELL_TYPE(VTK_BIQUADRATIC_TRIANGLE),
        CELL_TYPE(VTK_CUBIC_LINE),
        CELL_TYPE(VTK_CONVEX_POINT_SET),
        CELL_TYPE(VTK_POLYHEDRON),
        CELL_TYPE(VTK_PARAMETRIC_CURVE),
        CELL_TYPE(VTK_PARAMETRIC_SURFACE),
        CELL_TYPE(VTK_PARAMETRIC_TRI_SURFACE),
        CELL_TYPE(VTK_PARAMETRIC_QUAD_SURFACE),
        CELL_TYPE(VTK_PARAMETRIC_TETRA_REGION),
        CELL_TYPE(VTK_PARAMETRIC_HEX_REGION),
        CELL_TYPE(VTK_HIGHER_ORDER_EDGE),
        CELL_TYPE(VTK_HIGHER_ORDER_TRIANGLE),
        CELL_TYPE(VTK_HIGHER_ORDER_QUAD),
        CELL_TYPE(VTK_HIGHER_ORDER_POLYGON),
        CELL_TYPE(VTK_HIGHER_ORDER_TETRAHEDRON),
        CELL_TYPE(VTK_HIGHER_ORDER_WEDGE),
        CELL_TYPE(VTK_HIGHER_ORDER_PYRAMID),
        CELL_TYPE(VTK_HIGHER_ORDER_HEXAHEDRON),
        CELL_TYPE(VTK_LAGRANGE_CURVE),
        CELL_TYPE(VTK_LAGRANGE_TRIANGLE),
        CELL_TYPE(VTK_LAGRANGE_QUADRILATERAL),
        CELL_TYPE(VTK_LAGRANGE_TETRAHEDRON),
        CELL_TYPE(VTK_LAGRANGE_HEXAHEDRON),
        CELL_TYPE(VTK_LAGRANGE_WEDGE),
        CELL_TYPE(VTK_LAGRANGE_PYRAMID),
        CELL_TYPE(VTK_BEZIER_CURVE),
        CELL_TYPE(VTK_BEZIER_TRIANGLE),
        CELL_TYPE(VTK_BEZIER_QUADRILATERAL),
        CELL_TYPE(VTK_BEZIER_TETRAHEDRON),
        CELL_TYPE(VTK_BEZIER_HEXAHEDRON),
        CELL_TYPE(VTK_BEZIER_WEDGE),
        CELL_TYPE(VTK_BEZIER_PYRAMID)
    };
#undef CELL_TYPE

    auto it = cellTypeNames.find(cellType);
    if (it != cellTypeNames.end())
    {
        return it->second;
    }
    return "Unknown";
}
}
